#include <stdio.h>

#include "libs/goforc.h"
#include "libc/add.h"

int main() {
    // For call thirdlibs, generated by go
    printf("%lld\n", Foo(1, 2));
    Bar();

    // For call selflibs
    printf("%d\n", sadd(100, 200));
    return 0;
}

